/** Canonical sheet IDs from IA — no top-level routes for these. */
export const SHEET_TITLES: Record<string, string> = {
  "account.create": "حساب جدید",
  deposit: "واریز",
  withdraw: "برداشت",
  transfer: "انتقال",
  "income.create": "درآمد",
  "expense.create": "هزینه",
  "account.detail": "جزئیات حساب",
  "cheque.receive": "دریافت چک",
  "cheque.pay": "پرداخت چک",
  "transaction.detail": "جزئیات تراکنش",
  "crypto.buy": "خرید کریپتو",
  "crypto.sell": "فروش کریپتو",
  "crypto.transfer": "انتقال کریپتو",
  "crypto.c2c": "تبدیل C2C",
  "stocks.buy": "خرید سهام",
  "stocks.sell": "فروش سهام",
  "stocks.dividend": "سود سهام",
  "stocks.corporateAction": "رویداد شرکتی",
  "fund.subscribe": "خرید واحد صندوق",
  "fund.redeem": "ابطال واحد",
  "fund.nav": "ثبت NAV",
  "fund.distribution": "توزیع سود صندوق",
  "fund.reinvest": "سرمایه‌گذاری مجدد",
  "metals.buy": "خرید فلز",
  "metals.sell": "فروش فلز",
  "metals.delivery": "تحویل فیزیکی",
  "loan.create": "وام جدید",
  "loan.payment": "پرداخت وام",
  "loan.reversal": "برگشت پرداخت",
  "loan.schedule": "برنامه اقساط",
  "loan.fees": "کارمزد و جریمه",
  "loan.statement": "صورتحساب وام",
  backup: "پشتیبان",
  restore: "بازیابی",
  recovery: "بازیابی سیستم",
  import: "ورود داده",
  license: "مجوز و نسخه",
  settings: "تنظیمات",
  "price.sync": "همگام‌سازی قیمت",
  "tax.tools": "ابزار مالیات",
  reconcile: "سلامت داده / تطبیق",
  "report.trialBalance": "تراز آزمایشی",
  "report.balanceSheet": "ترازنامه",
  "report.incomeStatement": "سود و زیان",
  "report.cashFlow": "جریان وجوه نقد",
  "report.generalLedger": "دفتر کل",
  "report.netWorth": "ارزش خالص",
  "report.investmentHoldings": "موجودی سرمایه‌گذاری",
};

export const WIRED_SHEETS = new Set([
  "account.create",
  "deposit",
  "withdraw",
  "loan.create",
  "backup",
  "import",
  "license",
]);
